version: '3'
services:
  backend:
    build: ./backend
    environment:
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    volumes:
      - db-data:/data
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    environment:
      - VITE_GITHUB_CLIENT_ID=${VITE_GITHUB_CLIENT_ID}
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
