"""Compatibility wrapper for raw analysis-record helpers."""

from crits.services.analysis_records import (
    ANALYSIS_RECORD_SCHEMA_VERSION,
    AnalysisLogRecord,
    AnalysisRecord,
    append_analysis_log,
    append_analysis_results,
    count_analysis_records,
    create_analysis_record,
    create_analysis_record_from_task,
    delete_analysis_record_by_id,
    delete_analysis_records,
    find_analysis_records,
    finish_analysis_record,
    get_analysis_record,
    get_analysis_record_by_id,
    mark_analysis_error,
    update_analysis_record,
    update_analysis_record_from_task,
)

__all__ = [
    "ANALYSIS_RECORD_SCHEMA_VERSION",
    "AnalysisLogRecord",
    "AnalysisRecord",
    "append_analysis_log",
    "append_analysis_results",
    "count_analysis_records",
    "create_analysis_record",
    "create_analysis_record_from_task",
    "delete_analysis_record_by_id",
    "delete_analysis_records",
    "find_analysis_records",
    "finish_analysis_record",
    "get_analysis_record_by_id",
    "get_analysis_record",
    "mark_analysis_error",
    "update_analysis_record",
    "update_analysis_record_from_task",
]
