"""Default vocabulary values used by modern GraphQL TLO queries."""

DEFAULT_DOMAIN_RECORD_TYPES = ("A", "AAAA", "CNAME", "MX", "NS", "PTR", "SOA", "SRV", "TXT")

DEFAULT_IP_TYPES = (
    "IPv4 Address",
    "IPv4 Subnet",
    "IPv6 Address",
    "IPv6 Subnet",
)

DEFAULT_EVENT_TYPES = (
    "Application Compromise",
    "Denial of Service",
    "Distributed Denial of Service",
    "Exploitation",
    "Intel Sharing",
    "Malicious Code",
    "Phishing",
    "Privileged Account Compromise",
    "Scanning",
    "Sensor Alert",
    "Social Engineering",
    "Sniffing",
    "Spam",
    "Strategic Web Compromise",
    "Unauthorized Information Access",
    "Unknown",
    "Website Defacement",
)

DEFAULT_RELATIONSHIP_TYPES = (
    "Compressed From",
    "Compressed Into",
    "Connected From",
    "Connected To",
    "Contains",
    "Contained Within",
    "Created",
    "Created By",
    "Decoded",
    "Decoded By",
    "Decrypted",
    "Decrypted By",
    "Downloaded",
    "Downloaded By",
    "Downloaded From",
    "Downloaded To",
    "Dropped",
    "Dropped By",
    "Installed",
    "Installed By",
    "Loaded From",
    "Loaded Into",
    "Packed From",
    "Packed Into",
    "Received From",
    "Sent To",
    "Registered",
    "Registered To",
    "Related To",
    "Resolved To",
    "Sent",
    "Sent By",
    "Sub-domain Of",
    "Supra-domain Of",
)

DEFAULT_OBJECT_TYPES = (
    "Adjust Token",
    "API Key",
    "AS Name",
    "AS Number",
    "Bank account",
    "Base64 Alphabet",
    "Bitcoin account",
    "C2 URL",
    "Certificate Fingerprint",
    "Certificate Name",
    "Checksum CRC16",
    "Command Line",
    "Company name",
    "Cookie Name",
    "Country",
    "CRX",
    "Debug Path",
    "Debug String",
    "Destination Port",
    "Device IO",
    "Document from URL",
    "Document Metadata",
    "Domain",
    "Email Address",
    "Email Address From",
    "Email Address Sender",
    "Email Boundary",
    "Email Header Field",
    "Email HELO",
    "Email Message ID",
    "Email Originating IP",
    "Email Reply-To",
    "Email Subject",
    "Email X-Mailer",
    "Email X-Originating IP",
    "Encryption Key",
    "File Created",
    "File Deleted",
    "File Moved",
    "File Name",
    "File Opened",
    "File Path",
    "File Read",
    "File Upload",
    "File Written",
    "GET Parameter",
    "HEX String",
    "HTML ID",
    "HTTP Request",
    "HTTP Response Code",
    "IMPHASH",
    "IPv4 Address",
    "IPv4 Subnet",
    "IPv6 Address",
    "IPv6 Subnet",
    "Latitude",
    "Launch Agent",
    "Location",
    "Longitude",
    "MAC Address",
    "Malware Name",
    "MD5",
    "Memory Alloc",
    "Memory Protect",
    "Memory Read",
    "Memory Written",
    "Mutant Created",
    "Mutex",
    "Name Server",
    "Other File Operation",
    "Password",
    "Password Salt",
    "Payload Data",
    "Payload Type",
    "Pipe",
    "PIVY Group Name",
    "PIVY Password",
    "POST Data",
    "Process Name",
    "Protocol",
    "RC4 Key",
    "Referer",
    "Referer of Referer",
    "Registrar",
    "Registry Key",
    "Registry Key Created",
    "Registry Key Deleted",
    "Registry Key Enumerated",
    "Registry Key Monitored",
    "Registry Key Opened",
    "Registry Key Value Created",
    "Registry Key Value Deleted",
    "Registry Key Value Modified",
    "Registry Key Value Queried",
    "Service Name",
    "SHA1",
    "SHA256",
    "SMS Origin",
    "Source Port",
    "SSDEEP",
    "String",
    "Telephone",
    "Time Created",
    "Time Updated",
    "Tracking ID",
    "TS End",
    "TS Start",
    "URI",
    "URI Path",
    "User Agent",
    "User ID",
    "Victim IP",
    "Volume Queried",
    "Web Payload",
    "Webstorage Key",
    "WHOIS Address 1",
    "WHOIS Address 2",
    "WHOIS Name",
    "WHOIS Registrant Email Address",
    "XPI",
)

DEFAULT_SECTORS = (
    "Chemical",
    "Commercial Facilities",
    "Communications",
    "Critical Manufacturing",
    "Dams",
    "Defense Industrial Base",
    "Emergency Services",
    "Energy",
    "Financial Services",
    "Food and Agriculture",
    "Government Facilities",
    "Healthcare and Public Health",
    "Information Technology",
    "Nuclear Reactors Materials and Waste",
    "Transportation Systems",
    "Water and Wastewater Systems",
)

DEFAULT_INDICATOR_TYPES = (
    "Adjust Token",
    "API Key",
    "AS Number",
    "AS Name",
    "Bank account",
    "Bitcoin account",
    "Certificate Fingerprint",
    "Certificate Name",
    "Checksum CRC16",
    "Command Line",
    "Company name",
    "Cookie Name",
    "Country",
    "CRX",
    "Debug Path",
    "Debug String",
    "Destination Port",
    "Device IO",
    "Document from URL",
    "Domain",
    "Email Boundary",
    "Email Address",
    "Email Address From",
    "Email Header Field",
    "Email HELO",
    "Email Message ID",
    "Email Originating IP",
    "Email Reply-To",
    "Email Address Sender",
    "Email Subject",
    "Email X-Mailer",
    "Email X-Originating IP",
    "File Created",
    "File Deleted",
    "File Moved",
    "File Name",
    "File Opened",
    "File Path",
    "File Read",
    "File Written",
    "GET Parameter",
    "HEX String",
    "HTML ID",
    "HTTP Request",
    "HTTP Response Code",
    "IMPHASH",
    "IPv4 Address",
    "IPv4 Subnet",
    "IPv6 Address",
    "IPv6 Subnet",
    "Latitude",
    "Launch Agent",
    "Location",
    "Longitude",
    "MAC Address",
    "Malware Name",
    "MD5",
    "Memory Alloc",
    "Memory Protect",
    "Memory Read",
    "Memory Written",
    "Mutant Created",
    "Mutex",
    "Name Server",
    "Other File Operation",
    "Password",
    "Password Salt",
    "Payload Data",
    "Payload Type",
    "Pipe",
    "POST Data",
    "Process Name",
    "Protocol",
    "Referer",
    "Referer of Referer",
    "Registrar",
    "Registry Key",
    "Registry Key Created",
    "Registry Key Deleted",
    "Registry Key Enumerated",
    "Registry Key Monitored",
    "Registry Key Opened",
    "Registry Key Value Created",
    "Registry Key Value Deleted",
    "Registry Key Value Modified",
    "Registry Key Value Queried",
    "Service Name",
    "SHA1",
    "SHA256",
    "SMS Origin",
    "Source Port",
    "SSDEEP",
    "Telephone",
    "Time Created",
    "Time Updated",
    "Tracking ID",
    "TS End",
    "TS Start",
    "URI",
    "URI Path",
    "User Agent",
    "User ID",
    "Victim IP",
    "Volume Queried",
    "Webstorage Key",
    "Web Payload",
    "WHOIS Name",
    "WHOIS Address 1",
    "WHOIS Address 2",
    "WHOIS Registrant Email Address",
    "WHOIS Telephone",
    "XPI",
)
